/* eslint-disable @next/next/no-css-tags */
import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta charSet="utf-8" />
          {/* <title>Startup - Startup Website Template</title> */}
          {/* <meta content="Free HTML Templates" name="keywords" />
          <meta content="Free HTML Templates" name="description" /> */}

          {/* Favicon  */}
          <link href="img/favicon.ico" rel="icon" />

          {/* Google Web Fonts  */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="true"
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=Rubik:wght@400;500;600;700&display=swap"
            rel="stylesheet"
          />

          {/* Icon Font Stylesheet */}
          <link
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
            rel="stylesheet"
          />
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
            rel="stylesheet"
          />

          {/* Libraries Stylesheet  */}
          <link
            href="../assets/lib/owlcarousel/assets/owl.carousel.min.css"
            rel="stylesheet"
          />
          <link href="../assets/lib/animate/animate.min.css" rel="stylesheet" />

          {/* Customized Bootstrap Stylesheet  */}
          <link href="../assets/css/bootstrap.min.css" rel="stylesheet" />
          {/* 
     Template Stylesheet  */}
          <link href="../assets/css/style.css" rel="stylesheet" />

          {/* JavaScript Libraries  */}
          <script
            async
            src="https://code.jquery.com/jquery-3.4.1.min.js"
          ></script>
          <script
            async
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
          ></script>
          <script async src="../assets/lib/wow/wow.min.js"></script>
          <script async src="../assets/lib/easing/easing.min.js"></script>
          <script async src="../assets/lib/waypoints/waypoints.min.js"></script>
          <script async src="../assets/lib/counterup/counterup.min.js"></script>
          <script async src="../assets/lib/owlcarousel/owl.carousel.min.js" />

          {/* Template Javascript  */}
          <script async src="../assets/js/main.js"></script>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
